export const data = JSON.parse("{\"key\":\"v-a96541ce\",\"path\":\"/post/backend/jwt-springboot/\",\"title\":\"Xây dựng Json Web Token trong Spring Boot\",\"lang\":\"en-US\",\"frontmatter\":{\"layout\":\"Post\",\"title\":\"Xây dựng Json Web Token trong Spring Boot\",\"subtitle\":\"Phân quyền và đăng nhập trong Spring Boot\",\"author\":\"Trần Hữu Đang\",\"date\":\"2023-10-27T00:00:00.000Z\",\"useHeaderImage\":false,\"headerImage\":\"img/in-post/back-end/jwtspringboot.png\",\"headerMask\":\"rgba(70, 112, 80, 0)\",\"permalinkPattern\":\"/post/backend/:slug/\",\"tags\":[\"Backend\",\"Authentication\",\"Authoriztion\",\"SpringBoot\"]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"Xây dựng CSDL\",\"slug\":\"xay-dung-csdl\",\"children\":[{\"level\":3,\"title\":\"Mã nguồn My-SQL\",\"slug\":\"ma-nguon-my-sql\",\"children\":[{\"level\":4,\"title\":\"Tạo bảng\",\"slug\":\"tao-bang\",\"children\":[]},{\"level\":4,\"title\":\"Thêm dữ liệu\",\"slug\":\"them-du-lieu\",\"children\":[]}]}]},{\"level\":2,\"title\":\"Tạo dự án\",\"slug\":\"tao-du-an\",\"children\":[{\"level\":3,\"title\":\"Tạo dự án với Spring Tools Sute\",\"slug\":\"tao-du-an-voi-spring-tools-sute\",\"children\":[]},{\"level\":3,\"title\":\"Cấu hình các biến môi trường\",\"slug\":\"cau-hinh-cac-bien-moi-truong\",\"children\":[]}]},{\"level\":2,\"title\":\"Tạo các đối tượng Entities\",\"slug\":\"tao-cac-đoi-tuong-entities\",\"children\":[]},{\"level\":2,\"title\":\"Tạo các models tương tác Database\",\"slug\":\"tao-cac-models-tuong-tac-database\",\"children\":[{\"level\":3,\"title\":\"Lớp UserDAO\",\"slug\":\"lop-userdao\",\"children\":[]},{\"level\":3,\"title\":\"Repositories\",\"slug\":\"repositories\",\"children\":[]}]},{\"level\":2,\"title\":\"Tạo các Object Authentication\",\"slug\":\"tao-cac-object-authentication\",\"children\":[]},{\"level\":2,\"title\":\"Tạo các services\",\"slug\":\"tao-cac-services\",\"children\":[{\"level\":3,\"title\":\"Lớp JwtService\",\"slug\":\"lop-jwtservice\",\"children\":[]},{\"level\":3,\"title\":\"Lớp Authenticationservice\",\"slug\":\"lop-authenticationservice\",\"children\":[]}]},{\"level\":2,\"title\":\"Viết API\",\"slug\":\"viet-api\",\"children\":[{\"level\":3,\"title\":\"Viết api đăng nhập\",\"slug\":\"viet-api-đang-nhap\",\"children\":[]}]},{\"level\":2,\"title\":\"Lời kết\",\"slug\":\"loi-ket\",\"children\":[]},{\"level\":2,\"title\":\"Chú thích\",\"slug\":\"chu-thich\",\"children\":[{\"level\":4,\"title\":\"Spring\",\"slug\":\"spring\",\"children\":[]},{\"level\":4,\"title\":\"Token\",\"slug\":\"token\",\"children\":[]},{\"level\":4,\"title\":\"T-SQL\",\"slug\":\"t-sql\",\"children\":[]},{\"level\":4,\"title\":\"Front-end\",\"slug\":\"front-end\",\"children\":[]}]}],\"readingTime\":{\"minutes\":18,\"words\":2755},\"filePathRelative\":\"posts/backend/jwt-springboot.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
