export const data = JSON.parse("{\"key\":\"v-d1017e66\",\"path\":\"/post/backend/jwt-nodejs/\",\"title\":\"Xây dựng Json Web Token trong NodeJS\",\"lang\":\"en-US\",\"frontmatter\":{\"layout\":\"Post\",\"title\":\"Xây dựng Json Web Token trong NodeJS\",\"subtitle\":\"Phân quyền và đăng nhập trong NodeJS\",\"author\":\"Trần Hữu Đang\",\"date\":\"2023-10-20T00:00:00.000Z\",\"useHeaderImage\":false,\"headerImage\":\"img/in-post/back-end/jwtnodejs.png\",\"headerMask\":\"rgba(70, 112, 80, 0)\",\"permalinkPattern\":\"/post/backend/:slug/\",\"tags\":[\"Backend\",\"Authentication\",\"Authoriztion\"]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"Xây dựng CSDL\",\"slug\":\"xay-dung-csdl\",\"children\":[{\"level\":3,\"title\":\"Mã nguồn My-SQL\",\"slug\":\"ma-nguon-my-sql\",\"children\":[{\"level\":4,\"title\":\"Account\",\"slug\":\"account\",\"children\":[]},{\"level\":4,\"title\":\"Roles\",\"slug\":\"roles\",\"children\":[]},{\"level\":4,\"title\":\"UserRole\",\"slug\":\"userrole\",\"children\":[]}]}]},{\"level\":2,\"title\":\"Tạo dự án\",\"slug\":\"tao-du-an\",\"children\":[{\"level\":3,\"title\":\"Tạo dự án với Express\",\"slug\":\"tao-du-an-voi-express\",\"children\":[]},{\"level\":3,\"title\":\"Cài đặt thư viện cần thiết\",\"slug\":\"cai-đat-thu-vien-can-thiet\",\"children\":[]}]},{\"level\":2,\"title\":\"Lập trình back-end\",\"slug\":\"lap-trinh-back-end\",\"children\":[{\"level\":3,\"title\":\"Khởi tạo SECRET KEY\",\"slug\":\"khoi-tao-secret-key\",\"children\":[]},{\"level\":3,\"title\":\"Xây dựng JWT Model\",\"slug\":\"xay-dung-jwt-model\",\"children\":[]},{\"level\":3,\"title\":\"Xây dựng User Model\",\"slug\":\"xay-dung-user-model\",\"children\":[]},{\"level\":3,\"title\":\"Xây dựng User Controller\",\"slug\":\"xay-dung-user-controller\",\"children\":[]},{\"level\":3,\"title\":\"Xây dựng Router Login\",\"slug\":\"xay-dung-router-login\",\"children\":[]}]},{\"level\":2,\"title\":\"Lập trình Front-end\",\"slug\":\"lap-trinh-front-end\",\"children\":[{\"level\":3,\"title\":\"Xây dựng form đăng nhập\",\"slug\":\"xay-dung-form-đang-nhap\",\"children\":[]},{\"level\":3,\"title\":\"Xây dựng hàm call API bằng JQuery\",\"slug\":\"xay-dung-ham-call-api-bang-jquery\",\"children\":[]}]},{\"level\":2,\"title\":\"Chạy ứng dụng\",\"slug\":\"chay-ung-dung\",\"children\":[{\"level\":3,\"title\":\"Chạy ứng dụng phía back-end\",\"slug\":\"chay-ung-dung-phia-back-end\",\"children\":[]}]},{\"level\":2,\"title\":\"Chú thích\",\"slug\":\"chu-thich\",\"children\":[{\"level\":4,\"title\":\"SEAN APP\",\"slug\":\"sean-app\",\"children\":[]},{\"level\":4,\"title\":\"Token\",\"slug\":\"token\",\"children\":[]},{\"level\":4,\"title\":\"T-SQL\",\"slug\":\"t-sql\",\"children\":[]},{\"level\":4,\"title\":\"Front-end\",\"slug\":\"front-end\",\"children\":[]}]}],\"readingTime\":{\"minutes\":14,\"words\":2234},\"filePathRelative\":\"posts/backend/jwt-nodejs.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
