export const pagesRoutes = [
  ["v-31767f5b","/about/project.html",{"title":"Giới thiệu về dự án"},["/about/project","/about/project.md"]],
  ["v-74bc627b","/about/",{"title":"Khai vị"},["/about/index.html","/about/README.md"]],
  ["v-51f86e14","/docker/",{"title":""},["/docker/index.html","/docker/README.md"]],
  ["v-d3b8a592","/docker/section1.html",{"title":"Docker"},["/docker/section1","/docker/section1.md"]],
  ["v-7445ff36","/dsa/",{"title":"Lời nói đầu"},["/dsa/index.html","/dsa/readme.md"]],
  ["v-a3c54c30","/dsa/session1.html",{"title":"Tổng quan về DSA"},["/dsa/session1","/dsa/session1.md"]],
  ["v-a05b9af2","/dsa/session2.html",{"title":"Danh sách đặc"},["/dsa/session2","/dsa/session2.md"]],
  ["v-9cf1e9b4","/dsa/session3.html",{"title":"Danh sách liên kết"},["/dsa/session3","/dsa/session3.md"]],
  ["v-63e5b0be","/java-core/",{"title":"Lời nói đầu"},["/java-core/index.html","/java-core/readme.md"]],
  ["v-a1cf3540","/java-core/session1.html",{"title":"Bài 1. Giới thiệu về Java"},["/java-core/session1","/java-core/session1.md"]],
  ["v-9e658402","/java-core/session2.html",{"title":"Bài 2. Sử dụng biến, toán tử và các kiểu dữ liệu"},["/java-core/session2","/java-core/session2.md"]],
  ["v-9afbd2c4","/java-core/session3.html",{"title":"Bài 3. Cấu trúc rẽ nhánh"},["/java-core/session3","/java-core/session3.md"]],
  ["v-97922186","/java-core/session4.html",{"title":"Bài 4. Vòng lặp"},["/java-core/session4","/java-core/session4.md"]],
  ["v-94287048","/java-core/session5.html",{"title":"Bài 5. Mảng"},["/java-core/session5","/java-core/session5.md"]],
  ["v-90bebf0a","/java-core/session6.html",{"title":"Bài 6. Chuỗi"},["/java-core/session6","/java-core/session6.md"]],
  ["v-8d550dcc","/java-core/session7.html",{"title":"Bài 7. Phương thức"},["/java-core/session7","/java-core/session7.md"]],
  ["v-89eb5c8e","/java-core/session8.html",{"title":"Tổng kết. Bài tập cuối môn Java căn bản"},["/java-core/session8","/java-core/session8.md"]],
  ["v-6d2014de","/java-oop/",{"title":"Lời nói đầu"},["/java-oop/index.html","/java-oop/readme.md"]],
  ["v-2d29cf6d","/java-oop/session1.html",{"title":"Bài 1. Lập trình hướng đối tượng"},["/java-oop/session1","/java-oop/session1.md"]],
  ["v-2edea80c","/java-oop/session2.html",{"title":"Bài 2. Tính đa hình"},["/java-oop/session2","/java-oop/session2.md"]],
  ["v-309380ab","/java-oop/session3.html",{"title":"Bài 3. Tính kế thừa"},["/java-oop/session3","/java-oop/session3.md"]],
  ["v-3248594a","/java-oop/session4.html",{"title":"Bài 4. Tính đóng gói"},["/java-oop/session4","/java-oop/session4.md"]],
  ["v-33fd31e9","/java-oop/session5.html",{"title":"Bài 5. Tính trừu tượng"},["/java-oop/session5","/java-oop/session5.md"]],
  ["v-35b20a88","/java-oop/session6.html",{"title":"Bài 6. Những câu hỏi phỏng vấn Java OOP phổ biến nhất"},["/java-oop/session6","/java-oop/session6.md"]],
  ["v-6c67d393","/github/",{"title":"Lời nói đầu"},["/github/index.html","/github/readme.md"]],
  ["v-6c2644ab","/github/session1.html",{"title":"Bài 1. Setup môi trường"},["/github/session1","/github/session1.md"]],
  ["v-6ddb1d4a","/github/session2.html",{"title":"Bài 2. Đẩy code lên GitHub"},["/github/session2","/github/session2.md"]],
  ["v-6f8ff5e9","/github/session3.html",{"title":"Bài 3 Undo khi gặp một commit sai"},["/github/session3","/github/session3.md"]],
  ["v-7144ce88","/github/session4.html",{"title":"Bài 4 Làm việc nhóm"},["/github/session4","/github/session4.md"]],
  ["v-72f9a727","/github/session5.html",{"title":"Bài 5. Làm việc với nhánh"},["/github/session5","/github/session5.md"]],
  ["v-74ae7fc6","/github/session6.html",{"title":"Bài 6. Thao tác bằng GitHub Desktop"},["/github/session6","/github/session6.md"]],
  ["v-76635865","/github/session7.html",{"title":"Bài 7 Viết commits chuyên nghiệp"},["/github/session7","/github/session7.md"]],
  ["v-78183104","/github/session8.html",{"title":"Bài 8 Đóng góp mã nguồn mở"},["/github/session8","/github/session8.md"]],
  ["v-71df65a8","/java-collections/",{"title":"1. Tìm hiểu về Collections trong Java"},["/java-collections/index.html","/java-collections/readme.md"]],
  ["v-7457ebb2","/java-collections/session1.html",{"title":"2. List"},["/java-collections/session1","/java-collections/session1.md"]],
  ["v-16d88ef0","/java-collections/session10.html",{"title":"11. HashMap"},["/java-collections/session10","/java-collections/session10.md"]],
  ["v-188d678f","/java-collections/session11.html",{"title":"12. LinkedHashMap"},["/java-collections/session11","/java-collections/session11.md"]],
  ["v-1a42402e","/java-collections/session12.html",{"title":"13. TreeMap"},["/java-collections/session12","/java-collections/session12.md"]],
  ["v-1bf718cd","/java-collections/session13.html",{"title":"14. HashTable"},["/java-collections/session13","/java-collections/session13.md"]],
  ["v-1dabf16c","/java-collections/session14.html",{"title":"15. Enum"},["/java-collections/session14","/java-collections/session14.md"]],
  ["v-1f60ca0b","/java-collections/session15.html",{"title":"16. EnumMap"},["/java-collections/session15","/java-collections/session15.md"]],
  ["v-2115a2aa","/java-collections/session16.html",{"title":"17. EnumSet"},["/java-collections/session16","/java-collections/session16.md"]],
  ["v-22ca7b49","/java-collections/session17.html",{"title":"18. Sorted"},["/java-collections/session17","/java-collections/session17.md"]],
  ["v-247f53e8","/java-collections/session18.html",{"title":"Bài 6. Những câu hỏi phỏng vấn Java OOP phổ biến nhất"},["/java-collections/session18","/java-collections/session18.md"]],
  ["v-760cc451","/java-collections/session2.html",{"title":"3. ArrayList"},["/java-collections/session2","/java-collections/session2.md"]],
  ["v-77c19cf0","/java-collections/session3.html",{"title":"LinkedList"},["/java-collections/session3","/java-collections/session3.md"]],
  ["v-7976758f","/java-collections/session4.html",{"title":"5. So sánh ArrayList và LinkedList"},["/java-collections/session4","/java-collections/session4.md"]],
  ["v-7b2b4e2e","/java-collections/session5.html",{"title":"6. Set"},["/java-collections/session5","/java-collections/session5.md"]],
  ["v-7ce026cd","/java-collections/session6.html",{"title":"7. HashSet"},["/java-collections/session6","/java-collections/session6.md"]],
  ["v-7e94ff6c","/java-collections/session7.html",{"title":"8. LinkedHashSet"},["/java-collections/session7","/java-collections/session7.md"]],
  ["v-ff6c4fea","/java-collections/session8.html",{"title":"9. TreeSet"},["/java-collections/session8","/java-collections/session8.md"]],
  ["v-fc029eac","/java-collections/session9.html",{"title":"10. Map"},["/java-collections/session9","/java-collections/session9.md"]],
  ["v-2fe4ecaa","/nodejs/",{"title":"Lời nói đầu"},["/nodejs/index.html","/nodejs/readme.md"]],
  ["v-c27994da","/nodejs/session1.html",{"title":"Bài 1. Tìm hiểu về NodeJS"},["/nodejs/session1","/nodejs/session1.md"]],
  ["v-bf0fe39c","/nodejs/session2.html",{"title":"Bài 2. Tìm hiểu về Ejs"},["/nodejs/session2","/nodejs/session2.md"]],
  ["v-bba6325e","/nodejs/session3.html",{"title":"Bài 3. Làm việc với MySql"},["/nodejs/session3","/nodejs/session3.md"]],
  ["v-b83c8120","/nodejs/session4.html",{"title":"Bài 4. Lập trình MVC"},["/nodejs/session4","/nodejs/session4.md"]],
  ["v-b4d2cfe2","/nodejs/session5.html",{"title":"Bài 5. Giới thiệu Restful API"},["/nodejs/session5","/nodejs/session5.md"]],
  ["v-b1691ea4","/nodejs/session6.html",{"title":"Bài 6. Xây dựng Restful API"},["/nodejs/session6","/nodejs/session6.md"]],
  ["v-adff6d66","/nodejs/session7.html",{"title":"Bài 7. Xác thực và xác nhận người dùng"},["/nodejs/session7","/nodejs/session7.md"]],
  ["v-aa95bc28","/nodejs/session8.html",{"title":"Bài 8. Làm việc với MongoDB"},["/nodejs/session8","/nodejs/session8.md"]],
  ["v-f1eb35fc","/php-core/",{"title":"Lời nói đầu"},["/php-core/index.html","/php-core/readme.md"]],
  ["v-91bc80c8","/php-core/session1.html",{"title":"Bài 1. Giới thiệu về PHP"},["/php-core/session1","/php-core/session1.md"]],
  ["v-8e52cf8a","/php-core/session2.html",{"title":"Bài 2. Sử dụng các kiểu dữ liệu"},["/php-core/session2","/php-core/session2.md"]],
  ["v-8ae91e4c","/php-core/session3.html",{"title":"Bài 3. Hàm và HTML"},["/php-core/session3","/php-core/session3.md"]],
  ["v-877f6d0e","/php-core/session4.html",{"title":"Bài 4. Forms"},["/php-core/session4","/php-core/session4.md"]],
  ["v-8415bbd0","/php-core/session5.html",{"title":"Bài 5. File"},["/php-core/session5","/php-core/session5.md"]],
  ["v-80ac0a92","/php-core/session6.html",{"title":"Bài 6. MySQLi căn bản"},["/php-core/session6","/php-core/session6.md"]],
  ["v-7d425954","/php-core/session7.html",{"title":"Bài 7. MySQLi nâng cao"},["/php-core/session7","/php-core/session7.md"]],
  ["v-79d8a816","/php-core/session8.html",{"title":"Bài 8. Session, Cookie và PDO"},["/php-core/session8","/php-core/session8.md"]],
  ["v-d9adfd94","/spring-boot/",{"title":"Lời nói đầu"},["/spring-boot/index.html","/spring-boot/readme.md"]],
  ["v-58a4d030","/spring-boot/session1.html",{"title":"Bài 1. Rest Controllers"},["/spring-boot/session1","/spring-boot/session1.md"]],
  ["v-553b1ef2","/spring-boot/session2.html",{"title":"Bài 2. Components, Autowired và Bean"},["/spring-boot/session2","/spring-boot/session2.md"]],
  ["v-51d16db4","/spring-boot/session3.html",{"title":"Bài 3. GET API"},["/spring-boot/session3","/spring-boot/session3.md"]],
  ["v-4e67bc76","/spring-boot/session4.html",{"title":"Bài 4. DELETE API"},["/spring-boot/session4","/spring-boot/session4.md"]],
  ["v-4afe0b38","/spring-boot/session5.html",{"title":"Bài 5. POST API"},["/spring-boot/session5","/spring-boot/session5.md"]],
  ["v-479459fa","/spring-boot/session6.html",{"title":"Bài 6. PUT và PATCH API"},["/spring-boot/session6","/spring-boot/session6.md"]],
  ["v-442aa8bc","/spring-boot/session7.html",{"title":"Bài 7. SECURITY và JWT"},["/spring-boot/session7","/spring-boot/session7.md"]],
  ["v-40c0f77e","/spring-boot/session8.html",{"title":"Bài 8. Session, Cookie và PDO"},["/spring-boot/session8","/spring-boot/session8.md"]],
  ["v-2f9253b4","/sql-server/",{"title":"Lời nói đầu"},["/sql-server/index.html","/sql-server/readme.md"]],
  ["v-c0ba7bac","/sql-server/session1.html",{"title":"Tổng quan về hệ QT-CSDL"},["/sql-server/session1","/sql-server/session1.md"]],
  ["v-bd50ca6e","/sql-server/session2.html",{"title":"Tạo CSDL quan hệ và T-SQL"},["/sql-server/session2","/sql-server/session2.md"]],
  ["v-b9e71930","/sql-server/session3.html",{"title":"Các hàm hệ thống và xử lý chuỗi"},["/sql-server/session3","/sql-server/session3.md"]],
  ["v-b67d67f2","/sql-server/session4.html",{"title":"Điều kiện và vòng lặp"},["/sql-server/session4","/sql-server/session4.md"]],
  ["v-b313b6b4","/sql-server/session5.html",{"title":"Stored Procedures"},["/sql-server/session5","/sql-server/session5.md"]],
  ["v-afaa0576","/sql-server/session6.html",{"title":"Trigger"},["/sql-server/session6","/sql-server/session6.md"]],
  ["v-ac405438","/sql-server/session7.html",{"title":"Function và View"},["/sql-server/session7","/sql-server/session7.md"]],
  ["v-a8d6a2fa","/sql-server/session8.html",{"title":"Sao lưu và phục hồi CSDL"},["/sql-server/session8","/sql-server/session8.md"]],
  ["v-15551100","/tech/",{"title":"Links"},["/tech/index.html","/tech/README.md"]],
  ["v-2c4bd480","/posts/swing/qr-extension.html",{"title":""},["/posts/swing/qr-extension","/posts/swing/qr-extension.md"]],
  ["v-d1017e66","/post/backend/jwt-nodejs/",{"title":"Xây dựng Json Web Token trong NodeJS","subtitle":"Phân quyền và đăng nhập trong NodeJS","date":"2023-10-20T00:00:00.000Z","tags":["Backend","Authentication","Authoriztion"],"headerImage":"img/in-post/back-end/jwtnodejs.png","excerpt":""},["/post/backend/jwt-nodejs/index.html","/posts/backend/jwt-nodejs.html","/posts/backend/jwt-nodejs.md"]],
  ["v-a96541ce","/post/backend/jwt-springboot/",{"title":"Xây dựng Json Web Token trong Spring Boot","subtitle":"Phân quyền và đăng nhập trong Spring Boot","date":"2023-10-27T00:00:00.000Z","tags":["Backend","Authentication","Authoriztion","SpringBoot"],"headerImage":"img/in-post/back-end/jwtspringboot.png","excerpt":""},["/post/backend/jwt-springboot/index.html","/posts/backend/jwt-springboot.html","/posts/backend/jwt-springboot.md"]],
  ["v-77e2f3a3","/post/backend/session-cookie/",{"title":"Tìm hiểu về Session, Cookie trong Xác thực người dùng","subtitle":"Session, Cookie là gì?","date":"2023-09-03T00:00:00.000Z","tags":["Backend","Authentication","Authoriztion"],"headerImage":"img/in-post/back-end/session-cookie.png","excerpt":"<p>Trong mô hình <a href=\"\">CSR</a> hay Client-Side-Rendering việc lưu thông tin người dùng thường được xác định thông qua giá trị của Session...</p>\n"},["/post/backend/session-cookie/index.html","/posts/backend/session-cookie.html","/posts/backend/session-cookie.md"]],
  ["v-79e3325a","/post/backend/spam-request/",{"title":"Hạn chế Request nhận được từ một IP trong khoảng thời gian nhất định","subtitle":"Xây dựng server SpringBoot hạn chế Spam Request từ người dùng","date":"2023-12-22T00:00:00.000Z","tags":["Backend","Redis","Security"],"headerImage":"img/in-post/back-end/spam-request-filter.png","excerpt":""},["/post/backend/spam-request/index.html","/posts/backend/spam-request.html","/posts/backend/spam-request.md"]],
  ["v-9a2f84d6","/post/interview/java-core-interview/",{"title":"Các Câu Hỏi Phỏng Vấn Java Thường Gặp P.1","subtitle":"Ôn tập phỏng vấn cùng Ếch","date":"2023-11-01T00:00:00.000Z","tags":["interview","Java","Fresher"],"headerImage":"img/in-post/interview/session1.png","excerpt":""},["/post/interview/java-core-interview/index.html","/posts/interview/java-core-interview.html","/posts/interview/java-core-interview.md"]],
  ["v-4e3cf4fd","/post/interview/restful-api/",{"title":"Tìm hiểu về RestAPI và Restful API","subtitle":"Ôn tập phỏng vấn cùng Ếch","date":"2023-11-13T00:00:00.000Z","tags":["interview","Web","Junior","BackEnd"],"headerImage":"img/in-post/interview/api-banner.png","excerpt":""},["/post/interview/restful-api/index.html","/posts/interview/restful-api.html","/posts/interview/restful-api.md"]],
  ["v-0c96670e","/post/algorithm/greedy/",{"title":"Tìm hiểu về giải thuật tham lam","subtitle":"Cấu trúc dữ liệu và giải thuật","date":"2023-10-20T00:00:00.000Z","tags":["Algorithm","Thuật toán","Giải thuật"],"headerImage":"img/in-post/algorithm/greedy.png","excerpt":"<p>Thuật toán tham lam được ứng dụng nhiều rất vào các bài toán thực tế. Hãy cùng mình tìm hiểu nhé...</p>\n"},["/post/algorithm/greedy/index.html","/posts/algorithm/greedy.html","/posts/algorithm/greedy.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-15534fdd","/tags/",{"title":"Tags"},["/tags/index.html"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/index.html"]],
  ["v-a3ca2210","/tags/backend/",{"title":"Backend | Tags"},["/tags/backend/index.html"]],
  ["v-2d0a870d","/en/",{"title":"Home"},["/en/index.html"]],
  ["v-1405c73a","/tags/authentication/",{"title":"Authentication | Tags"},["/tags/authentication/index.html"]],
  ["v-f4a6573c","/tags/authoriztion/",{"title":"Authoriztion | Tags"},["/tags/authoriztion/index.html"]],
  ["v-97a514da","/tags/springboot/",{"title":"SpringBoot | Tags"},["/tags/springboot/index.html"]],
  ["v-0a640031","/tags/redis/",{"title":"Redis | Tags"},["/tags/redis/index.html"]],
  ["v-c1ceac9c","/tags/security/",{"title":"Security | Tags"},["/tags/security/index.html"]],
  ["v-f06f832a","/tags/interview/",{"title":"interview | Tags"},["/tags/interview/index.html"]],
  ["v-d6eea6e0","/tags/java/",{"title":"Java | Tags"},["/tags/java/index.html"]],
  ["v-567587de","/tags/fresher/",{"title":"Fresher | Tags"},["/tags/fresher/index.html"]],
  ["v-cd148e90","/tags/web/",{"title":"Web | Tags"},["/tags/web/index.html"]],
  ["v-9276cbae","/tags/junior/",{"title":"Junior | Tags"},["/tags/junior/index.html"]],
  ["v-f25e8d86","/tags/algorithm/",{"title":"Algorithm | Tags"},["/tags/algorithm/index.html"]],
  ["v-f70da1b4","/tags/thu%E1%BA%ADt-to%C3%A1n/",{"title":"Thuật toán | Tags"},["/tags/thuật-toán/","/tags/thu%E1%BA%ADt-to%C3%A1n/index.html"]],
  ["v-8274e990","/tags/gi%E1%BA%A3i-thu%E1%BA%ADt/",{"title":"Giải thuật | Tags"},["/tags/giải-thuật/","/tags/gi%E1%BA%A3i-thu%E1%BA%ADt/index.html"]],
  ["v-379daf6e","/en/tags/",{"title":"Tags"},["/en/tags/index.html"]],
  ["v-3a1f8885","/page/1/",{"title":"Home"},["/page/1/index.html"]],
]
